spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: userService
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

#Eureka Configurations
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.1.7:8761/eureka}
  instance:
    preferIpAddress: true

server:
  port: 9090
